### ISSUE TITLE
Expiry is not populated while first run 

### ISSUE THREAD

**Issue by sudhakarsi** [Tapanhaz/Shoonya_OptionChainStreamer#1]
we don't get expiry for following code

def get_atm_strike(self, ltp):
        return round(ltp/self.strikediff)*self.strikediff

also above code will not yield anything

**Comment by sudhakarsi** [comment]
expiry is not populated in isWithinSixDays(input_date,expiryDate):

**Comment by Tapanhaz** [comment]
You should use latest pandas. Otherwise it will not work.

**Comment by sudhakarsi** [comment]
Version is up to date 

C:\Users\Sudhakar>pip show pandas

DEPRECATION: Loading egg at c:\use

Name: pandas

Version: 2.0.1

**Comment by Tapanhaz** [comment]
There is a typo in the requirements.txt . We have to install httpx with http2 support to work it correctly. The issue has been fixed now
