### ISSUE TITLE
video not playing..

### ISSUE THREAD

**Issue by tarakbluru** [Tapanhaz/Shoonya_OptionChainStreamer#2]
On my browser, seeing this.. can you please help..

![image](https://github.com/Tapanhaz/Shoonya_OptionChainStreamer/assets/1935750/ebae6502-5c26-400f-bac2-4bdbd402bbf8)

thanks.

**Comment by Tapanhaz** [comment]
You are using firefox ? If so, try in chrome once.. it should run .

**Comment by Tapanhaz** [comment]
The video I uploaded earlier is h264 webm but unfortunately firefox supports only vp6 / vp9 encoded webm. so I reuploaded it.. It should work now

**Comment by Tapanhaz** [comment]
I am going to close this issue as all of my tried browsers played that well. If the issue remains please open a new issue.
